CRITICAL - 2021-11-17 04:45:32 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-1' at line 7
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT `a`.*, `...')
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\BaseConnection.php(741): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `a`.*, `...')
#2 D:\Server\htdocs\pcare_nov_2021\system\Database\BaseConnection.php(669): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `a`.*, `...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT `a`.*, `...', Array, false)
#4 D:\Server\htdocs\pcare_nov_2021\app\Modules\Report\Models\Report_model.php(280): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Server\htdocs\pcare_nov_2021\app\Modules\Report\Controllers\Report.php(89): App\Modules\Report\Models\Report_model->getsalesreportList(Array)
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(920): App\Modules\Report\Controllers\Report->bdtask_ChecksalesreportList()
#7 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(406): CodeIgniter\CodeIgniter->runController(Object(App\Modules\Report\Controllers\Report))
#8 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-11-17 05:02:40 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:40 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:42 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:42 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:44 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:44 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:47 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:47 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:50 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:50 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:52 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:52 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:53 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:53 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:57 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:57 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:57 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:57 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:02:57 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:02:57 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:05 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:05 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:07 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:07 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:07 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:07 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:10 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:10 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:12 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:12 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:12 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:12 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:17 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:17 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:17 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:17 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:20 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:20 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:24 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:24 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:27 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:27 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:33 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:33 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:35 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:35 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:41 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:41 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:46 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:46 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:03:52 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:03:52 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:03 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:03 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:05 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:05 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:07 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:07 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:09 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:09 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:11 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:11 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:13 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:13 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:15 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:15 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:17 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:17 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:17 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:17 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:19 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:19 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:26 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:26 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:28 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:28 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:28 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:28 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:30 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:30 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:30 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:30 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:32 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:32 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:33 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:33 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:33 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:33 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:36 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:36 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:38 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:38 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:40 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:40 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:41 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:41 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:43 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:43 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:48 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:48 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:50 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:50 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:07:53 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:07:53 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:10:54 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:10:54 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:10:56 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:10:56 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:10:58 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:10:58 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:00 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:00 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:01 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:01 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:03 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:03 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:05 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:05 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:07 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:07 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:07 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:07 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:09 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:09 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:16 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:16 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:18 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:18 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:18 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:18 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:19 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:19 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:19 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:19 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:21 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:21 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:23 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:23 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:23 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:23 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:25 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:25 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:27 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:27 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:29 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:29 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:31 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:31 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:32 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:32 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:36 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:36 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:38 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:38 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-17 05:11:40 --> Unable to connect to the database.
#0 D:\Server\htdocs\pcare_nov_2021\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\Server\htdocs\pcare_nov_2021\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#2 D:\Server\htdocs\pcare_nov_2021\system\Controller.php(138): CodeIgniter\Database\Config::forge()
#3 D:\Server\htdocs\pcare_nov_2021\app\Modules\Invoice\Controllers\BaseController.php(39): CodeIgniter\Controller->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#4 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(893): App\Modules\Invoice\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#5 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(401): CodeIgniter\CodeIgniter->createController()
#6 D:\Server\htdocs\pcare_nov_2021\system\CodeIgniter.php(314): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\Server\htdocs\pcare_nov_2021\index.php(62): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-11-17 05:11:40 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\Server\\htdoc...', 100, Array)
#1 D:\Server\htdocs\pcare_nov_2021\app\Views\errors\html\error_exception.php(100): print_r(Object(CodeIgniter\Database\MySQLi\Connection), true)
#2 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(308): include('D:\\Server\\htdoc...')
#3 D:\Server\htdocs\pcare_nov_2021\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
